# FROM node:14.17.6

# RUN mkdir -p /app/server/node_modules && chown -R node:node /app/server


# WORKDIR /app/server

# COPY package*.json ./

# USER node

# RUN npm install

# COPY --chown=node:node . .

# EXPOSE 8080

# CMD [ "node", "index.js"]


FROM node:14.17.6

WORKDIR /app/server
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 8080
RUN  chown -R node /app/server
USER node

CMD [ "npm", "api"]